name: DP-VirtualStorage
version: 1.2.0
main: com.darksoldier1404.dpvs.VirtualStorage
authors: [ DEAD_POOLIO_ ]
api-version: 1.20
depend:
  - DPP-Core
  - PlaceholderAPI
commands:
  dpvs:
    aliases: [ virtualstorage, 창고, 가상창고 ]